# Generated by Django 5.0.1 on 2024-01-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
