# Generated by Django 5.0.1 on 2024-01-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('minium', models.PositiveIntegerField()),
                ('sum_per_km', models.PositiveIntegerField()),
                ('waiting_cost', models.PositiveIntegerField()),
                ('baggage_cost', models.PositiveIntegerField()),
                ('bonus_percent', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('photo', models.FileField(blank=True, null=True, upload_to='drivers')),
                ('car_type', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('sms_code', models.CharField(max_length=7)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('gender', models.CharField(default='Erkak', max_length=10)),
                ('has_baggage', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.carcategory')),
            ],
        ),
    ]
