# Generated by Django 5.0.1 on 2024-01-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-id']},
        ),
    ]
